version: '2'
services:
  database-virtuoso:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
    expose:
     - "1112"
     - "8891"
    ports:
     - "1112:1111"
     - "8891:8890"
    environment:
     - DBA_PASSWORD=myDbaPassword
     - SPARQL_UPDATE=true
     - DEFAULT_GRAPH=http://www.example.com/my-graph

  weaver-database-virtuoso:
    image: sysunite/weaver-database-virtuoso:0.0.8
    expose:
     - "9475"
    ports:
     - "9475:9475"
    depends_on:
     - database-virtuoso
    links:
     - database-virtuoso
    environment:
      - WEAVER_VIRTUOSO_SERVICE_PORT=9475
      - VIRTUOSO_DB_USER=dba
      - VIRTUOSO_DB_PASSWORD=myDbaPassword
      - VIRTUOSO_DB_PATH=jdbc:virtuoso://database-virtuoso:1111

  file-system:
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=NYLEXGR6MF2IE99LZ4UE
      - MINIO_SECRET_KEY=CjMuTRwYPcneXnGac2aQH0J+EdYdehTW4Cw7bZGD
    command: server /data
