version: '2'
services:
  database:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
    expose:
     - "1111"
     - "8890"
    ports:
     - "1111:1111"
     - "8890:8890"
    environment:
     - DBA_PASSWORD=myDbaPassword
     - SPARQL_UPDATE=true
     - DEFAULT_GRAPH=http://www.example.com/my-graph

  weaver-database-virtuoso:
    image: sysunite/weaver-database-virtuoso:0.0.10
    expose:
     - "9474"
    ports:
     - "9474:9474"
    depends_on:
     - database
    links:
     - database
    environment:
      - WEAVER_VIRTUOSO_SERVICE_PORT=9474
      - VIRTUOSO_DB_USER=dba
      - VIRTUOSO_DB_PASSWORD=myDbaPassword
      - VIRTUOSO_DB_PATH=jdbc:virtuoso://database:1111

  file-system:
    image: minio/minio
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=NYLEXGR6MF2IE99LZ4UE
      - MINIO_SECRET_KEY=CjMuTRwYPcneXnGac2aQH0J+EdYdehTW4Cw7bZGD
    command: server /data
