version: '2.1'
services:
  postgres:
    image: postgres:9.6-alpine
    volumes:
    - ./postgresql:/var/lib/postgresql/data
    expose:
    - "5432"
    ports:
    - "5432:5432"

  postgresql-connector:
    image: sysunite/weaver-database-postgresql:0.0.24
    links:
    - postgres
    expose:
    - "4567"
    ports:
    - "4567:4567"
    environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=root

  file-system:
    image: minio/minio:RELEASE.2017-04-25T01-27-49Z
    expose:
    - "9000"
    ports:
    - "9000:9000"
    environment:
    - MINIO_ACCESS_KEY=NYLEXGR6MF2IE99LZ4UE
    - MINIO_SECRET_KEY=CjMuTRwYPcneXnGac2aQH0J+EdYdehTW4Cw7bZGD
    command: server /data

  digioffice:
    restart: always
    image: sysunite/digioffice-node-service:0.0.1
    expose:
    - "2121"
    ports:
    - "2121:2121"
    environment:
    - DIGIOFFICE_ENDPOINT=https://doapigw20171.dotest.nl
    - DIGIOFFICE_PASS=RelSvcAcc2017
    - DIGIOFFICE_USER=RelaticsSvcAccount@dotest.nl
    - DIGIOFFICE_PROJECT_ocmsMINUSrijnland=1
    - DIGIOFFICE_PROJECT_ocmsMINUSrijnlandMINUStest=1
    - DIGIOFFICE_PROJECT_ocmsMINUSeefde=1
    - DIGIOFFICE_PROJECT_ocmsMINUSeefdeMINUStest=1
    - DIGIOFFICE_PROJECT_eefde=1
