version: '2.1'
services:
  file-system:
    image: minio/minio:RELEASE.2017-04-25T01-27-49Z
    expose:
    - "9000"
    ports:
    - "9000:9000"
    environment:
    - MINIO_ACCESS_KEY=NYLEXGR6MF2IE99LZ4UE
    - MINIO_SECRET_KEY=CjMuTRwYPcneXnGac2aQH0J+EdYdehTW4Cw7bZGD
    command: server /data
