version: '2'
services:
  tenforce-virtuoso:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
    expose:
     - "1111"
     - "8890"
    ports:
     - "1111:1111"
     - "8890:8890"
    environment:
     - DBA_PASSWORD=myDbaPassword
     - SPARQL_UPDATE=true
     - DEFAULT_GRAPH=http://www.example.com/my-graph

  weaver-database-virtuoso:
    image: sysunite/weaver-database-virtuoso:0.0.4
    expose:
     - "9474"
    ports:
     - "9474:9474"
    depends_on:
     - tenforce-virtuoso
    links:
     - tenforce-virtuoso
    environment:
      - WEAVER_VIRTUOSO_SERVICE_PORT=9474
      - VIRTUOSO_DB_USER=dba
      - VIRTUOSO_DB_PASSWORD=myDbaPassword
      - VIRTUOSO_DB_PATH=jdbc:virtuoso://tenforce-virtuoso:1111
      
  mongodb:
    image: mongo:latest
    volumes:
     - './data:/data/db'
    expose:
     - "27017"
    command: ["mongod", "--smallfiles"]
    
  weaverflock:
    image: sysunite/weaver-flock:0.0.7 
    environment:
     MONGODB_URI: "mongodb://mongodb:27017/weavernest"
    ports:
     - "4567:4567"
    links:
     - mongodb