// Generated by CoffeeScript 1.10.0
(function() {
  var Server, conf, i, j, len, len1, path, paths, run, runlist;

  paths = ['admin', 'application', 'auth', 'comm', 'database'];

  for (i = 0, len = paths.length; i < len; i++) {
    path = paths[i];
    require('app-module-path').addPath('src/' + path);
  }

  runlist = ['./routes', 'ApplicationCtrl', 'NodeCtrl', 'AuthCtrl'];

  for (j = 0, len1 = runlist.length; j < len1; j++) {
    run = runlist[j];
    require(run);
  }

  Server = require('server');

  conf = require('config');

  new Server({
    port: conf.get('server.weaver.port'),
    routes: 'weaver'
  }).run();

  new Server({
    port: conf.get('server.admin.port'),
    routes: 'admin',
    host: 'localhost'
  }).run();

  require('colors');

  console.log(require('splash/splash').cyan);

}).call(this);
