// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(bus) {
    return bus["private"]("countNodes").retrieve('project').on(function(req, project) {
      return 500;
    });
  };

}).call(this);
